version: '3'
services:
  app:
    build: ./
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
      - "5005:5005"
    command: sh ./docker-entrypoint.sh
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/colaboreja
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: colaboreja
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    restart: always
